### ISSUE TITLE
Not running on ARM-based Macbook

### ISSUE THREAD

**Issue by grizant** [adknudson/Bigsimr.jl#45]
Running the basic example on macOS Monterey version 12.6 Macbook Air (M1, 2020), Apple M1 chip, 8 GB memory gives an error:

`using Bigsimr
using Distributions
target_corr = cor_randPD(3)
margins = [Binomial(20, 0.2), Beta(2, 3), LogNormal(3, 1)]
adjusted_corr = pearson_match(target_corr, margins)
`

`System max size of single shmem segment(MB) : 4
System max size of all shmem segments(MB) : 16
Requested size(MB) : 0
Please ensure requested size is within system limits.
If not, increase system limits and try again.
ERROR: SystemError: shm_open() failed for /jl0523077VZeXFV0382WpI7AOojS: Permission denied
Stacktrace:
 [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
   @ Base ./error.jl:174
 [2] #systemerror#68
   @ ./error.jl:173 [inlined]
 [3] systemerror
   @ ./error.jl:173 [inlined]
 [4] _shm_mmap_array(T::Type, dims::Tuple{Int64, Int64}, shm_seg_name::String, mode::UInt16)
   @ SharedArrays /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/SharedArrays/src/SharedArrays.jl:681
 [5] shm_mmap_array(T::Type, dims::Tuple{Int64, Int64}, shm_seg_name::String, mode::UInt16)
   @ SharedArrays /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/SharedArrays/src/SharedArrays.jl:651
 [6] (::SharedArrays.var"#6#9"{Float64, Tuple{Int64, Int64}})()
   @ SharedArrays /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/SharedArrays/src/SharedArrays.jl:128
 [7] run_work_thunk(thunk::SharedArrays.var"#6#9"{Float64, Tuple{Int64, Int64}}, print_error::Bool)
   @ Distributed /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:63
 [8] run_work_thunk
   @ /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:72 [inlined]
 [9] (::Distributed.var"#96#98"{Distributed.RemoteValue, SharedArrays.var"#6#9"{Float64, Tuple{Int64, Int64}}})()
   @ Distributed ./task.jl:423
Stacktrace:
 [1] wait_ref
   @ /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Distributed/src/remotecall.jl:577 [inlined]
 [2] call_on_owner
   @ /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Distributed/src/remotecall.jl:567 [inlined]
 [3] wait(r::Distributed.Future)
   @ Distributed /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Distributed/src/remotecall.jl:590
 [4] SharedArrays.SharedMatrix{Float64}(dims::Tuple{Int64, Int64}; init::Bool, pids::Vector{Int64})
   @ SharedArrays /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/SharedArrays/src/SharedArrays.jl:137
 [5] SharedArray
   @ /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/SharedArrays/src/SharedArrays.jl:105 [inlined]
 [6] #_#10
   @ /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/SharedArrays/src/SharedArrays.jl:161 [inlined]
 [7] SharedArray
   @ /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/SharedArrays/src/SharedArrays.jl:161 [inlined]
 [8] pearson_match(ρ::Matrix{Float64}, margins::Vector{UnivariateDistribution})
   @ Bigsimr ~/.julia/packages/Bigsimr/6ZN04/src/PearsonMatching/pearson_match.jl:178
 [9] top-level scope
   @ REPL[5]:1`

**Comment by adknudson** [comment]
Try updating to Julia v1.8 and get the latest Bigsimr version by starting Julia, getting into package mode and typing

```julia
add Bigsimr#master
test Bigsimr
```

**Comment by grizant** [comment]
All tests passed! Thank you @adknudson well done.

**Comment by adknudson** [comment]
Cool! I will tag a new release version with the changes.
